---
- ansible.builtin.import_tasks: packages.yml
- ansible.builtin.import_tasks: files.yml
- name: systemd | Populate service facts
  service_facts:
- name: systemd | Enable scanservjs service
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    daemon_reload: true
    name: scanservjs
